// <auto-generated />
namespace Paragraff.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class book_title_unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book_title_unique));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121451000_book_title_unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
