// <auto-generated />
namespace Paragraff.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class postaddrowsisreadistradable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postaddrowsisreadistradable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712281422457_post-add-rows-isread-istradable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
