// <auto-generated />
namespace Paragraff.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class postcomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postcomments));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271318130_post-comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
