// <auto-generated />
namespace Paragraff.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class userposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userposts));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231538360_user-posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
