// <auto-generated />
namespace Paragraff.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class bookhasmanywishers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookhasmanywishers));
        
        string IMigrationMetadata.Id
        {
            get { return "201801201820077_book-has-many-wishers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
